import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('home rooms open separately from chat settings, not the home directory', () => {
  const sidebar = read('../../src/components/layout/Sidebar.tsx')
  const settings = read('../../src/components/chat/ChatSettings.tsx')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.doesNotMatch(sidebar, /id: 'timeline'/)
  assert.doesNotMatch(sidebar, /id: 'notes'/)
  assert.doesNotMatch(sidebar, /id: 'diary'/)
  assert.doesNotMatch(sidebar, /id: 'photos'/)
  assert.doesNotMatch(sidebar, /id: 'poems'/)
  assert.doesNotMatch(sidebar, /id: 'stories'/)
  assert.doesNotMatch(sidebar, /id: 'research'/)
  assert.doesNotMatch(sidebar, /id: 'dreams'/)
  assert.doesNotMatch(sidebar, /id: 'memory'/)
  assert.match(settings, /row\('小纸条'.*onNotes/)
  assert.match(settings, /row\('日记'.*onDiary/)
  assert.match(settings, /row\('照片'.*onPhotos/)
  assert.match(settings, /row\('共诗'.*onPoems/)
  assert.match(settings, /row\('枕边集'.*onStories/)
  assert.match(settings, /row\('星野手记'.*onResearch/)
  assert.match(settings, /row\('愿望清单'.*onWishlist/)
  assert.match(settings, /row\('Timeline'.*onTimeline/)
  assert.match(settings, /row\('Tesis'.*onTesis/)
  assert.match(settings, /menu: '房间'/)
  assert.doesNotMatch(settings, /row\('摘要'/)
  assert.doesNotMatch(settings, /切换模型/)
  assert.match(chat, />SP<\/button>[\s\S]*>摘要<\/button>[\s\S]*>书签<\/button>[\s\S]*>模型<\/button>[\s\S]*>参数<\/button>/)
  assert.match(chat, /setModelDialogOpen\(true\)[\s\S]*>模型<\/button>/)
  assert.match(chat, /roomPanel === 'notes' \? <NotesView \/>/)
  assert.match(chat, /roomPanel === 'diary' \? <DiaryView \/>/)
  assert.match(chat, /roomPanel === 'photos' \? <PhotosView \/>/)
  assert.match(chat, /roomPanel === 'poems' \? <PoemsView \/>/)
  assert.match(chat, /roomPanel === 'stories' \? <StoriesView \/>/)
  assert.match(chat, /roomPanel === 'research' \? <ResearchView \/>/)
  assert.match(chat, /roomPanel === 'wake' \? <DreamsView fixedTab="reality" \/>/)
  assert.match(chat, /roomPanel === 'wishlist' \? <WishlistView \/>/)
  assert.match(chat, />心跳唤醒<\/button>/)
  assert.match(chat, /roomPanel === 'memory' \? <MemoryView \/>/)
  assert.match(chat, />记忆<\/button>/)
  assert.match(chat, /continueSession\(50\)[\s\S]*>换窗<\/button>/)
  assert.doesNotMatch(chat, /携带最近 50 条/)
  assert.match(chat, /'pt-7'/)
  assert.match(chat, /space-y-1 pt-1[\s\S]*grid grid-cols-5[\s\S]*grid grid-cols-3/)
  assert.doesNotMatch(chat, /搜索会话/)
  assert.match(chat, /roomPanel === 'timeline' \? <TimelineView \/>/)
})

test('CC controls stay compact until expanded', () => {
  const picker = read('../../src/features/chat/components/ChatRoutePicker.tsx')

  assert.match(picker, /<details/)
  assert.match(picker, /<summary[\s\S]*Claude Code/)
  assert.match(picker, /<select[\s\S]*CC_MODELS\.map/)
  assert.match(picker, /<select[\s\S]*availableCcEfforts/)
  assert.doesNotMatch(picker, /Claude Code · \{model\.name\}/)
})

test('night chat uses the ink blue paper palette', () => {
  const palette = read('../../tailwind.config.ts')
  const styles = read('../../src/styles/globals.css')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.match(palette, /bg: '#111B25'/)
  assert.match(palette, /surface: '#182632'/)
  assert.match(palette, /amber: '#CFA7A2'/)
  assert.match(palette, /text: '#F2EEE7'/)
  assert.match(styles, /\.dark \.bg-night-bg[\s\S]*repeating-linear-gradient/)
  assert.match(chat, /n \? 'bg-night-amber\/45 text-night-text'/)
  assert.match(chat, /border-night-amber\/40/)
  assert.match(chat, /aria-label=\{n \? '切换到日间模式' : '切换到夜间模式'\}/)
  assert.match(chat, /onClick=\{toggleTheme\}/)
})

test('chat rooms keep the night palette and compact reading type', () => {
  const coupons = read('../../src/components/coupons/CouponsView.tsx')
  const todo = read('../../src/components/todo/TodoView.tsx')
  const wheel = read('../../src/components/chat/IntimacyWheelModal.tsx')
  const tesis = read('../../src/components/tesis/TesisView.tsx')
  const poems = read('../../src/components/poems/PoemsView.tsx')
  const stories = read('../../src/components/stories/StoriesView.tsx')
  const research = read('../../src/components/research/ResearchView.tsx')

  assert.match(coupons, /bg-night-surface text-night-text/)
  assert.match(todo, /todo-receipt-night/)
  assert.match(wheel, /bg-night-surface text-night-text/)
  assert.doesNotMatch(wheel, /bg-gradient-to-r from-\[#873f58\]/)
  assert.match(tesis, /night \? '#CFA7A2' : '#b78680'/)
  assert.match(poems, /whitespace-pre-wrap font-serif text-sm leading-7/)
  assert.match(stories, /space-y-3 font-serif text-sm leading-6/)
  assert.match(research, /whitespace-pre-wrap text-justify text-sm leading-6/)
})

test('compact rooms reveal details on demand', () => {
  const coupons = read('../../src/components/coupons/CouponsView.tsx')
  const notes = read('../../src/components/notes/NotesView.tsx')
  const diary = read('../../src/components/diary/DiaryView.tsx')
  const stories = read('../../src/components/stories/StoriesView.tsx')
  const research = read('../../src/components/research/ResearchView.tsx')
  const wishlist = read('../../src/components/wishlist/WishlistView.tsx')
  const timeline = read('../../src/components/timeline/TimelineView.tsx')
  const summaries = read('../../src/components/chat/SummaryDialog.tsx')

  assert.match(coupons, /expandedId/)
  assert.match(coupons, /role="dialog" aria-modal="true" aria-label="签发一张券"/)
  assert.match(notes, /isExpanded && hasReplies/)
  assert.doesNotMatch(diary, /line-clamp-2 leading-relaxed/)
  assert.match(diary, /entry\.author === 'star' \? '🐆' : '🦦'/)
  assert.match(wishlist, /setExpanded\(value => !value\)/)
  assert.match(wishlist, /flex items-center gap-2 px-3 py-3[\s\S]*onClick=\{toggleDone\}[\s\S]*onClick=\{\(\) => setExpanded/)
  assert.match(stories, /aria-label="返回枕边集"/)
  assert.match(research, /aria-label="返回星野手记"/)
  assert.match(timeline, /h-\[600px\]/)
  assert.match(timeline, /md:grid-cols-2/)
  assert.match(summaries, /updateStageSummary/)
  assert.match(summaries, /deleteStageSummary/)
  assert.match(summaries, /onRegenerateStage/)
})
