import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('home rooms open separately from chat settings, not the home directory', () => {
  const sidebar = read('../../src/components/layout/Sidebar.tsx')
  const settings = read('../../src/components/chat/ChatSettings.tsx')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.doesNotMatch(sidebar, /id: 'timeline'/)
  assert.doesNotMatch(sidebar, /id: 'notes'/)
  assert.doesNotMatch(sidebar, /id: 'diary'/)
  assert.doesNotMatch(sidebar, /id: 'photos'/)
  assert.doesNotMatch(sidebar, /id: 'poems'/)
  assert.doesNotMatch(sidebar, /id: 'stories'/)
  assert.doesNotMatch(sidebar, /id: 'research'/)
  assert.doesNotMatch(sidebar, /id: 'dreams'/)
  assert.doesNotMatch(sidebar, /id: 'memory'/)
  assert.match(settings, /row\('小纸条'.*onNotes/)
  assert.match(settings, /row\('日记'.*onDiary/)
  assert.match(settings, /row\('照片'.*onPhotos/)
  assert.match(settings, /row\('共诗'.*onPoems/)
  assert.match(settings, /row\('枕边集'.*onStories/)
  assert.match(settings, /row\('星野手记'.*onResearch/)
  assert.match(settings, /row\('愿望清单'.*onWishlist/)
  assert.match(settings, /row\('书影记录'.*onMedia/)
  assert.match(settings, /row\('Timeline'.*onTimeline/)
  assert.match(settings, /row\('Tesis'.*onTesis/)
  assert.match(settings, /menu: '房间'/)
  assert.doesNotMatch(settings, /row\('摘要'/)
  assert.doesNotMatch(settings, /切换模型/)
  assert.match(chat, />SP<\/button>[\s\S]*>模型<\/button>[\s\S]*>参数<\/button>[\s\S]*>换窗<\/button>[\s\S]*>摘要<\/button>[\s\S]*>书签<\/button>[\s\S]*>唤醒<\/button>[\s\S]*>记忆<\/button>/)
  assert.match(chat, /setModelDialogOpen\(true\)[\s\S]*>模型<\/button>/)
  assert.match(chat, /roomPanel === 'notes' \? <NotesView \/>/)
  assert.match(chat, /roomPanel === 'diary' \? <DiaryView \/>/)
  assert.match(chat, /roomPanel === 'photos' \? <PhotosView \/>/)
  assert.match(chat, /roomPanel === 'poems' \? <PoemsView \/>/)
  assert.match(chat, /roomPanel === 'stories' \? <StoriesView \/>/)
  assert.match(chat, /roomPanel === 'research' \? <ResearchView \/>/)
  assert.match(chat, /roomPanel === 'wake' \? <DreamsView fixedTab="reality" \/>/)
  assert.match(chat, /roomPanel === 'wishlist' \? <WishlistView \/>/)
  assert.match(chat, /roomPanel === 'media' \? <MediaLibraryView \/>/)
  assert.match(chat, />唤醒<\/button>/)
  assert.match(chat, /roomPanel === 'memory' \? <MemoryView \/>/)
  assert.match(chat, />记忆<\/button>/)
  assert.match(chat, /continueSession\(50\)[\s\S]*>换窗<\/button>/)
  assert.doesNotMatch(chat, /携带最近 50 条/)
  assert.match(chat, /'pt-11'/)
  assert.match(chat, /space-y-1\.5 pt-1[\s\S]*grid grid-cols-4 gap-1\.5[\s\S]*grid grid-cols-4 gap-1\.5/)
  assert.doesNotMatch(chat, /搜索会话/)
  assert.match(chat, /roomPanel === 'timeline' \? <TimelineView \/>/)
})

test('CC controls stay compact until expanded', () => {
  const picker = read('../../src/features/chat/components/ChatRoutePicker.tsx')

  assert.match(picker, /<details/)
  assert.match(picker, /<summary[\s\S]*Claude Code/)
  assert.match(picker, /<select[\s\S]*CC_MODELS\.map/)
  assert.match(picker, /<select[\s\S]*availableCcEfforts/)
  assert.match(picker, /activeRoute !== 'claude-code'[\s\S]*onSelectCc\(activeCcModel\)[\s\S]*使用 Claude Code/)
  assert.doesNotMatch(picker, /Claude Code · \{model\.name\}/)
})

test('night chat uses the ink blue paper palette', () => {
  const palette = read('../../tailwind.config.ts')
  const styles = read('../../src/styles/globals.css')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.match(palette, /bg: '#111B25'/)
  assert.match(palette, /surface: '#182632'/)
  assert.match(palette, /amber: '#CFA7A2'/)
  assert.match(palette, /text: '#F2EEE7'/)
  assert.match(styles, /\.dark \.bg-night-bg[\s\S]*repeating-linear-gradient/)
  assert.match(chat, /n \? 'bg-night-amber\/45 text-night-text'/)
  assert.match(chat, /border-night-amber\/40/)
  assert.match(chat, /aria-label=\{n \? '切换到日间模式' : '切换到夜间模式'\}/)
  assert.match(chat, /onClick=\{toggleTheme\}/)
})

test('star replies and thinking stay left aligned on transparent paper', () => {
  const chat = read('../../src/components/chat/ChatView.tsx')
  const streaming = read('../../src/features/chat/components/StreamingReply.tsx')

  assert.doesNotMatch(chat, /text-justify \[text-justify:inter-ideograph\]/)
  assert.doesNotMatch(streaming, /text-justify \[text-justify:inter-ideograph\]/)
  assert.doesNotMatch(chat, /text-\[13px\] p-2 rounded-lg overflow-hidden whitespace-pre-wrap/)
  assert.doesNotMatch(streaming, /text-\[13px\] p-2 rounded-lg whitespace-pre-wrap/)
  assert.match(chat, /<MarkdownText content=\{block\.content\}\/>/)
  assert.match(chat, /<MarkdownText content=\{msg\.thinking\}\/>/)
  assert.match(streaming, /<MarkdownText content=\{block\.content\} cursor=\{isLast\}\/>/)
  assert.match(chat, /useLayoutEffect\(\(\) => \{[\s\S]*el\.scrollTop = el\.scrollHeight[\s\S]*bottomedSessionRef\.current = sessionId/)
  assert.match(chat, /const toggleThinking = \(id: string\) => \{[\s\S]*stickBottomRef\.current = false[\s\S]*scrollRef\.current\.scrollTop = top/)
})

test('chat rooms keep the night palette and compact reading type', () => {
  const coupons = read('../../src/components/coupons/CouponsView.tsx')
  const todo = read('../../src/components/todo/TodoView.tsx')
  const wheel = read('../../src/components/chat/IntimacyWheelModal.tsx')
  const tesis = read('../../src/components/tesis/TesisView.tsx')
  const poems = read('../../src/components/poems/PoemsView.tsx')
  const stories = read('../../src/components/stories/StoriesView.tsx')
  const research = read('../../src/components/research/ResearchView.tsx')
  const notes = read('../../src/components/notes/NotesView.tsx')
  const guestbook = read('../../src/components/notes/GuestbookBoard.tsx')
  const chatSettings = read('../../src/components/chat/ChatSettings.tsx')
  const diary = read('../../src/components/diary/DiaryView.tsx')
  const photos = read('../../src/components/photos/PhotosView.tsx')
  const wishlist = read('../../src/components/wishlist/WishlistView.tsx')
  const media = read('../../src/components/media/MediaLibraryView.tsx')
  const coread = read('../../src/components/media/CoreadReader.tsx')
  const timeline = read('../../src/components/timeline/TimelineView.tsx')
  const dreams = read('../../src/components/dreams/DreamsView.tsx')
  const memory = read('../../src/components/memory/MemoryView.tsx')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.match(coupons, /bg-night-surface text-night-text/)
  assert.match(todo, /todo-receipt-night/)
  assert.match(wheel, /bg-night-surface text-night-text/)
  assert.doesNotMatch(wheel, /bg-gradient-to-r from-\[#873f58\]/)
  assert.match(tesis, /night \? '#CFA7A2' : '#b78680'/)
  assert.match(poems, /whitespace-pre-wrap font-serif text-sm leading-7/)
  assert.match(stories, /<MarkdownText content=\{body\}\/>/)
  assert.match(research, /<MarkdownText content=\{entry\.content\}\/>/)
  assert.doesNotMatch(chat, /<h2 className="font-serif text-lg">\{roomLabels\[roomPanel\]\}<\/h2>/)
  assert.doesNotMatch(notes, /🧲/)
  assert.doesNotMatch(diary, /📔/)
  assert.doesNotMatch(tesis, /📄 论文进度/)
  assert.match(media, /shareToChat\([\s\S]*kind: 'media'/)
  assert.match(media, /aria-label="分享到 Chat"/)
  assert.match(media, /grid-cols-3[\s\S]*sm:grid-cols-4[\s\S]*lg:grid-cols-6/)
  assert.match(media, /loading="lazy" decoding="async"/)
  assert.match(coread, /pendingProgress[\s\S]*return flushProgress/)
  for (const room of [notes, diary, photos, poems, stories, research, wishlist, media, timeline, tesis, dreams, memory]) assert.match(room, /bg-night-bg/)
  assert.match(notes, /<Pin[^>]*\/>[\s\S]*小纸条/)
  assert.match(notes, /<MessageSquareWarning[^>]*\/>[\s\S]*告状簿/)
  assert.match(notes, /<GuestbookBoard actor="fire" endpoint="\/api\/guestbook\?mark_read=1"/)
  assert.match(guestbook, /kind: 'guestbook'/)
  assert.match(guestbook, /aria-label="分享到 Chat"/)
  assert.match(chatSettings, /guestbookUnread/)
  assert.match(chatSettings, /lumbre-guestbook-read/)
  assert.match(photos, /<Camera[^>]*\/>照片墙/)
  assert.doesNotMatch(dreams, /💓|🔥|📝|☀️|🌙|🎲|🍂/)
})

test('compact rooms reveal details on demand', () => {
  const coupons = read('../../src/components/coupons/CouponsView.tsx')
  const notes = read('../../src/components/notes/NotesView.tsx')
  const diary = read('../../src/components/diary/DiaryView.tsx')
  const stories = read('../../src/components/stories/StoriesView.tsx')
  const research = read('../../src/components/research/ResearchView.tsx')
  const wishlist = read('../../src/components/wishlist/WishlistView.tsx')
  const timeline = read('../../src/components/timeline/TimelineView.tsx')
  const summaries = read('../../src/components/chat/SummaryDialog.tsx')

  assert.match(coupons, /expandedId/)
  assert.match(coupons, /role="dialog" aria-modal="true" aria-label="签发一张券"/)
  assert.match(notes, /isExpanded && hasReplies/)
  assert.doesNotMatch(diary, /line-clamp-2 leading-relaxed/)
  assert.match(diary, /entry\.author === 'star' \? '🐆' : '🦦'/)
  assert.match(wishlist, /setExpanded\(value => !value\)/)
  assert.match(wishlist, /flex items-center gap-2 px-3 py-3[\s\S]*onClick=\{toggleDone\}[\s\S]*onClick=\{\(\) => setExpanded/)
  assert.match(stories, /aria-label="返回枕边集"/)
  assert.match(research, /aria-label="返回星野手记"/)
  assert.match(timeline, /h-\[600px\]/)
  assert.match(timeline, /md:grid-cols-2/)
  assert.match(summaries, /updateStageSummary/)
  assert.match(summaries, /deleteStageSummary/)
  assert.match(summaries, /onRegenerateStage/)
})

test('room polish keeps dialogs and night surfaces inside the shared theme', () => {
  const chat = read('../../src/components/chat/ChatView.tsx')
  const notes = read('../../src/components/notes/NotesView.tsx')
  const diary = read('../../src/components/diary/DiaryView.tsx')
  const poems = read('../../src/components/poems/PoemsView.tsx')
  const stories = read('../../src/components/stories/StoriesView.tsx')
  const research = read('../../src/components/research/ResearchView.tsx')
  const timeline = read('../../src/components/timeline/TimelineView.tsx')
  const memory = read('../../src/components/memory/MemoryView.tsx')
  const coupons = read('../../src/components/coupons/CouponsView.tsx')
  const wheel = read('../../src/components/chat/IntimacyWheelModal.tsx')
  const models = read('../../src/components/chat/ModelDialog.tsx')
  const summaries = read('../../src/components/chat/SummaryDialog.tsx')
  const photos = read('../../src/components/photos/PhotosView.tsx')
  const wishlist = read('../../src/components/wishlist/WishlistView.tsx')
  const timer = read('../../src/components/timeline/TimelineTimerModal.tsx')

  for (const room of [notes, diary, poems, stories, timeline, memory, coupons, wheel, models, summaries]) {
    assert.doesNotMatch(room, /window\.(?:confirm|prompt)|\bconfirm\(/)
  }
  assert.doesNotMatch(photos, /\balert\(/)
  for (const room of [stories, research, poems]) {
    assert.doesNotMatch(room, /#(?:8e5263|7d789d|7d4658|a75f70|9d5361|32444b|3a323f|708e91)/i)
  }
  assert.doesNotMatch(wishlist, /想要的都写下来/)
  assert.doesNotMatch(timer, /时间会从点击开始后正向流动/)
  assert.doesNotMatch(chat, /<header className=\{`flex justify-end border-b/)
  assert.match(poems, /<PaperActionDialog/)
})
