import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('home rooms open separately from chat settings, not the home directory', () => {
  const sidebar = read('../../src/components/layout/Sidebar.tsx')
  const settings = read('../../src/components/chat/ChatSettings.tsx')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.doesNotMatch(sidebar, /id: 'timeline'/)
  assert.doesNotMatch(sidebar, /id: 'notes'/)
  assert.doesNotMatch(sidebar, /id: 'diary'/)
  assert.doesNotMatch(sidebar, /id: 'photos'/)
  assert.doesNotMatch(sidebar, /id: 'poems'/)
  assert.doesNotMatch(sidebar, /id: 'stories'/)
  assert.doesNotMatch(sidebar, /id: 'research'/)
  assert.doesNotMatch(sidebar, /id: 'dreams'/)
  assert.doesNotMatch(sidebar, /id: 'memory'/)
  assert.match(settings, /row\('小纸条'.*onNotes/)
  assert.match(settings, /row\('日记'.*onDiary/)
  assert.match(settings, /row\('照片'.*onPhotos/)
  assert.match(settings, /row\('共诗'.*onPoems/)
  assert.match(settings, /row\('枕边集'.*onStories/)
  assert.match(settings, /row\('星野手记'.*onResearch/)
  assert.match(settings, /row\('愿望清单'.*onWishlist/)
  assert.match(settings, /row\('Timeline'.*onTimeline/)
  assert.match(settings, /row\('Tesis'.*onTesis/)
  assert.match(settings, /menu: '房间'/)
  assert.doesNotMatch(settings, /row\('摘要'/)
  assert.match(chat, />SP<\/button>[\s\S]*>摘要<\/button>[\s\S]*>书签<\/button>[\s\S]*>模型<\/button>[\s\S]*>参数<\/button>/)
  assert.match(chat, /roomPanel === 'notes' \? <NotesView \/>/)
  assert.match(chat, /roomPanel === 'diary' \? <DiaryView \/>/)
  assert.match(chat, /roomPanel === 'photos' \? <PhotosView \/>/)
  assert.match(chat, /roomPanel === 'poems' \? <PoemsView \/>/)
  assert.match(chat, /roomPanel === 'stories' \? <StoriesView \/>/)
  assert.match(chat, /roomPanel === 'research' \? <ResearchView \/>/)
  assert.match(chat, /roomPanel === 'wake' \? <DreamsView fixedTab="reality" \/>/)
  assert.match(chat, /roomPanel === 'wishlist' \? <WishlistView \/>/)
  assert.match(chat, />💓 心跳唤醒<\/button>/)
  assert.match(chat, /roomPanel === 'memory' \? <MemoryView \/>/)
  assert.match(chat, />🧠 记忆庭院<\/button>/)
  assert.match(chat, /roomPanel === 'timeline' \? <TimelineView \/>/)
})

test('night chat uses the ink blue paper palette', () => {
  const palette = read('../../tailwind.config.ts')
  const styles = read('../../src/styles/globals.css')
  const chat = read('../../src/components/chat/ChatView.tsx')

  assert.match(palette, /bg: '#111B25'/)
  assert.match(palette, /surface: '#182632'/)
  assert.match(palette, /amber: '#CFA7A2'/)
  assert.match(palette, /text: '#F2EEE7'/)
  assert.match(styles, /\.dark \.bg-night-bg[\s\S]*repeating-linear-gradient/)
  assert.match(chat, /n \? 'bg-night-amber\/45 text-night-text'/)
  assert.match(chat, /border-night-amber\/40/)
  assert.match(chat, /aria-label=\{n \? '切换到日间模式' : '切换到夜间模式'\}/)
  assert.match(chat, /onClick=\{toggleTheme\}/)
})
