'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Check, ChevronDown, ChevronRight, FileText, Flag, Loader2, Lock, Pencil, RotateCcw, Trash2, Unlock, X } from 'lucide-react'
import { useTheme } from '@/lib/theme'
import { ChatSession, ChatSummary, useChatStore } from '@/lib/chatStore'
import { formatMadrid } from '@/lib/madrid-time'
import { pendingSummaryRounds, messagesAfterSummaryAnchor } from '@/lib/chat-summary'

export function SummaryDialog({ open, onClose, session, generating, stageGenerating, error, onGenerate, onRegenerate }: {
  open: boolean; onClose: () => void; session?: ChatSession; generating?: boolean; stageGenerating?: boolean; error?: string; onGenerate: () => void; onRegenerate: (summary: ChatSummary) => void
}) {
  const { theme } = useTheme(); const n = theme === 'night'
  const { settings, deleteSummary, updateSummary, updateSessionSummaryConfig } = useChatStore()
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState('')
  const [deleteTarget, setDeleteTarget] = useState<ChatSummary | null>(null)
  const config = session?.summaryConfig || { autoEnabled: true, turnSize: settings.summaryTurnSize, injectCount: settings.summaryInjectCount, modeVersion: 2 as const }
  const pending = pendingSummaryRounds(messagesAfterSummaryAnchor(session?.messages || [], config.anchorMessageId, config.anchorTimestamp), session?.summaries || []).length
  const summaries = [...(session?.summaries || [])].sort((a,b)=>b.endAt-a.endAt)
  const visibleSummaries = summaries.slice(0, 10)
  const stages = [...(session?.stageSummaries || [])].sort((a,b)=>b.endAt-a.endAt)
  const visibleStages = stages.slice(0, 10)
  const selectedProfile = settings.apiProfiles.find(p=>p.id===config.profileId) || settings.apiProfiles.find(p=>p.id===settings.activeProfileId) || settings.apiProfiles[0]
  const selectedModel = config.modelId || (selectedProfile?.id===settings.activeProfileId ? settings.model : selectedProfile?.defaultModel) || selectedProfile?.models[0]?.id || ''
  const patch = (value: any) => session && updateSessionSummaryConfig(session.id, value)
  const toggle = (id: string) => setExpanded(prev=>{const x=new Set(prev);x.has(id)?x.delete(id):x.add(id);return x})
  const card = n ? 'bg-night-surface border-night-border' : 'bg-white border-day-border'
  return <AnimatePresence>{open && <>
    <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose} className="fixed inset-0 z-[72] bg-black/40 backdrop-blur-sm"/>
    <motion.div initial={{opacity:0,scale:.96,y:12}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.96,y:12}} className={`fixed z-[73] inset-x-0 mx-auto w-[min(620px,calc(100vw-2rem))] max-h-[82dvh] overflow-y-auto rounded-2xl shadow-2xl ${n?'bg-night-card text-night-text':'bg-[#faf9f5] text-day-text'}`} style={{top:'max(calc(env(safe-area-inset-top,0px) + 8dvh),8dvh)'}}>
      <div className="sticky top-0 z-10 px-5 py-4 flex items-center justify-between bg-inherit border-b border-current/10"><div><h3 className="text-lg font-medium flex items-center gap-2"><FileText size={18}/>摘要</h3></div><button onClick={onClose} className="p-2 opacity-60"><X size={20}/></button></div>
      <div className="p-5 space-y-5">
        <div className={`rounded-2xl border p-4 space-y-4 ${card}`}>
          <div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">自动整理</p></div><button onClick={()=>patch({autoEnabled:!config.autoEnabled})} className={`relative w-14 h-8 rounded-full p-1 shadow-inner flex-shrink-0 ${config.autoEnabled?(n?'bg-night-amber':'bg-gradient-to-r from-day-pink to-[#f58b9f]'):(n?'bg-night-bg border border-night-border':'bg-gray-200 border border-gray-300')}`}><motion.span animate={{x:config.autoEnabled?24:0}} transition={{type:'spring',stiffness:500,damping:30}} className="block w-6 h-6 rounded-full bg-white shadow-md"/></button></div>
          <div><p className="text-xs font-medium mb-2">带入对话的普通摘要：{config.injectCount}张</p><input type="range" min={3} max={10} step={1} value={config.injectCount} onChange={e=>patch({injectCount:Number(e.target.value)})} className="w-full"/><div className="flex justify-between text-[9px] opacity-40"><span>3</span><span>10</span></div></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><label className="text-[10px] opacity-60">摘要 API<select value={selectedProfile?.id||''} onChange={e=>{const p=settings.apiProfiles.find(x=>x.id===e.target.value);patch({profileId:p?.id,modelId:p?.defaultModel||p?.models[0]?.id})}} className={`mt-1 w-full rounded-xl border px-3 py-2 text-xs bg-transparent ${n?'border-night-border':'border-day-border'}`}>{settings.apiProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-[10px] opacity-60">摘要模型<select value={selectedModel} onChange={e=>patch({profileId:selectedProfile?.id,modelId:e.target.value})} className={`mt-1 w-full rounded-xl border px-3 py-2 text-xs bg-transparent ${n?'border-night-border':'border-day-border'}`}>{(selectedProfile?.models||[]).map(m=><option key={m.id} value={m.id}>{m.name||m.id}</option>)}</select></label></div>
          <div className={`rounded-xl px-3 py-2 text-[11px] ${n?'bg-night-bg/60':'bg-[#fff6f3]'}`}>尚未整理：{pending}轮 · 自动阈值{config.turnSize}轮{stageGenerating?' · 正在压缩阶段摘要…':''}</div>
          {error && <div role="alert" className={`rounded-xl px-3 py-2 text-[11px] leading-5 ${n?'bg-red-950/30 text-red-200':'bg-red-50 text-red-600'}`}>{error}</div>}
          <button onClick={onGenerate} disabled={generating||pending<1} className={`w-full py-2.5 rounded-xl text-xs flex justify-center gap-2 disabled:opacity-40 ${n?'bg-night-amber text-night-bg':'bg-day-pink text-white'}`}>{generating?<Loader2 size={14} className="animate-spin"/>:<FileText size={14}/>}整理当前新增对话</button>
        </div>

        {!!stages.length && <div className="space-y-2"><div className="flex justify-between text-xs"><b>阶段摘要</b><span className="opacity-45">共{stages.length}张</span></div>{visibleStages.map(stage=><div key={stage.id} className={`rounded-2xl border ${card}`}><button onClick={()=>toggle(stage.id)} className="w-full p-4 flex gap-2 text-left">{expanded.has(stage.id)?<ChevronDown size={15}/>:<ChevronRight size={15}/>}<div className="min-w-0"><p className="text-sm font-medium truncate">{stage.title}</p><p className="text-[10px] opacity-45">{formatMadrid(stage.startAt,false)} — {formatMadrid(stage.endAt,false)} · 10张来源</p></div></button>{expanded.has(stage.id)&&<p className="px-4 pb-4 pl-11 text-sm leading-7 whitespace-pre-wrap">{stage.content}</p>}</div>)}</div>}

        <div className="space-y-3"><div className="flex justify-between text-xs"><b>最近的普通摘要</b><span className="opacity-45">共{summaries.length}张</span></div>{!visibleSummaries.length&&<div className="text-center py-8 text-xs opacity-40">还没有新摘要。</div>}
          {visibleSummaries.map(item=>{const isOpen=expanded.has(item.id),edit=editing===item.id;return <div key={item.id} className={`rounded-2xl border ${card} ${item.needsCorrection?'ring-1 ring-red-400/60':''}`}><div className="p-3 flex gap-2"><button onClick={()=>toggle(item.id)} className="p-1 opacity-60">{isOpen?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button><button onClick={()=>toggle(item.id)} className="min-w-0 flex-1 text-left"><p className="text-[10px] opacity-45">{formatMadrid(item.startAt,false)} — {formatMadrid(item.endAt,false)} · {item.turnCount}轮</p><p className="text-sm truncate mt-1">{item.eventSummary}</p><p className="text-[9px] mt-1 opacity-55">{item.locked?'🔒 已锁定 ':''}{item.needsCorrection?'⚑ 待纠错 ':''}{item.editedAt?'已编辑':''}</p></button><button title={item.locked?'解锁':'锁定'} onClick={()=>session&&updateSummary(session.id,item.id,{locked:!item.locked})} className="p-1 opacity-45">{item.locked?<Lock size={13}/>:<Unlock size={13}/>}</button><button title={item.locked?'摘要已锁定':'纠错标记'} disabled={item.locked} onClick={()=>session&&updateSummary(session.id,item.id,{needsCorrection:!item.needsCorrection})} className={`p-1 disabled:opacity-20 ${item.needsCorrection?'text-red-500':'opacity-35'}`}><Flag size={13}/></button></div>{isOpen&&<div className="px-4 pb-4 pl-11 border-t border-current/10 pt-3">{edit&&!item.locked?<><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={10} className={`w-full rounded-xl p-3 text-xs leading-relaxed outline-none ${n?'bg-night-card':'bg-gray-50'}`}/><div className="flex justify-end gap-3 mt-2"><button onClick={()=>setEditing(null)} className="text-xs opacity-50">取消</button><button onClick={()=>{if(draft.trim()&&session)updateSummary(session.id,item.id,{eventSummary:draft.trim(),needsCorrection:false,editedAt:Date.now()});setEditing(null)}} className={`text-xs flex gap-1 items-center ${n?'text-night-amber':'text-day-pink'}`}><Check size={12}/>保存</button></div></>:<><p className="text-sm leading-7 whitespace-pre-wrap">{item.eventSummary}</p><div className="flex flex-wrap gap-2 mt-3"><button disabled={item.locked} onClick={()=>{setEditing(item.id);setDraft(item.eventSummary)}} className="px-3 py-1.5 rounded-lg border border-current/15 text-[10px] flex gap-1 disabled:opacity-35"><Pencil size={11}/>{item.locked?'已锁定':'编辑纠错'}</button><button disabled={generating||item.locked} onClick={()=>onRegenerate(item)} className="px-3 py-1.5 rounded-lg border border-current/15 text-[10px] flex gap-1 disabled:opacity-35"><RotateCcw size={11}/>{item.locked?'已锁定':'重新生成'}</button><button disabled={item.locked} onClick={()=>setDeleteTarget(item)} className="ml-auto px-3 py-1.5 text-red-500 text-[10px] flex gap-1 disabled:opacity-30"><Trash2 size={11}/>{item.locked?'锁定保护中':'删除'}</button></div></>}</div>}</div>})}
        </div>
      </div>
    </motion.div>
    <AnimatePresence>{deleteTarget && <><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[74] bg-black/45" onClick={()=>setDeleteTarget(null)}/><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} className={`fixed z-[75] left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[min(360px,calc(100vw-2rem))] rounded-2xl p-5 shadow-2xl ${n?'bg-night-surface text-night-text':'bg-white text-day-text'}`}><h4 className="font-medium">确认删除这张摘要？</h4><p className="mt-2 text-xs leading-5 opacity-60">删除后无法撤销，引用它的阶段摘要也会失效。若要长期保护，请先锁定而不是删除。</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setDeleteTarget(null)} className="px-4 py-2 rounded-xl text-xs border border-current/15">取消</button><button onClick={()=>{if(session&&deleteTarget&&!deleteTarget.locked)deleteSummary(session.id,deleteTarget.id);setDeleteTarget(null)}} className="px-4 py-2 rounded-xl text-xs bg-red-500 text-white">确认删除</button></div></motion.div></>}</AnimatePresence>
  </>}</AnimatePresence>
}
